name: mlog
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  #fire_base
  cloud_firestore: ^3.4.4
  firebase_core: ^1.20.1
#  firebase_messaging: ^12.0.2
  firebase_auth:
  firebase_storage:
  #state
  get: ^4.6.1
  get_storage: ^2.0.3
  shared_preferences: ^2.0.1
  #share
  share_plus:
  #fonts
  google_fonts: ^2.1.0
  font_awesome_flutter: ^10.1.0
  #network images
  cached_network_image: ^3.2.0
  logger: ^1.1.0
  oktoast: ^3.1.5
  #ui
  cupertino_icons: ^1.0.2
  gap: ^2.0.0
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  top_snackbar_flutter: ^2.1.1
  bot_toast: ^4.0.1
  google_sign_in: ^5.4.1
  image_picker:
  path_provider: ^2.0.9
  custom_check_box: ^0.0.4
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
